name: Falcon Cloud Security CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  falcon-iac-scan:
    name: Falcon FCS IaC Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Falcon FCS IaC Scan
        uses: crowdstrike/fcs-action@v4.0.1
        with:
          falcon_client_id: ${{ secrets.FALCON_CLIENT_ID }}
          falcon_region: us-2
          scan_type: iac
          path: ./
          upload_results: true
          project_name: falcon-cnapp-poc
        env:
          FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
